// ---------------------------------------------------------------------------
// jsx-runtime.d.ts — hand-authored ambient types for TypeScript's automatic
// JSX transform (`"jsx": "react-jsx"` + `"jsxImportSource": "@esmj/dom"`).
//
// This file is NOT generated by tsup — it is copied verbatim into
// dist/jsx-runtime.d.ts by the `build` script (see package.json), and is
// also referenced as the `types` entry for the `./jsx-dev-runtime` export,
// since both runtime entry points share the exact same JSX shape.
//
// Deliberate simplification: `IntrinsicElements` uses a loose index
// signature rather than per-tag strict attribute typing (e.g. no distinct
// `button` vs `img` attribute sets). Consumers wanting stricter checking can
// augment this namespace themselves.
//
// Note on `Fragment`'s type: the `type` parameter below is typed as the
// widened `symbol` rather than `typeof Fragment` (a nominal `unique symbol`).
// `Fragment` is also re-exported from the main `@esmj/dom` entry point (its
// type there is generated separately by tsup from the real
// `export const Fragment = Symbol('Fragment')` in createElement.mjs). Two
// independently-declared `unique symbol` types are never mutually assignable
// even when they refer to the same runtime value, so using the nominal type
// here would make `createElement(Fragment, ...)` fail to type-check when
// `Fragment` was imported from `@esmj/dom` instead of `@esmj/dom/jsx-runtime`.
// Widening to `symbol` accepts either.
// ---------------------------------------------------------------------------

/** Marker for `<>...</>` fragment syntax — see createElement.mjs. */
export declare const Fragment: unique symbol;

/** Automatic-runtime factory for elements with zero or one child. */
export declare function jsx(
  type: string | Function | symbol,
  props: Record<string, unknown> | null,
  key?: string | number,
): unknown;

/** Automatic-runtime factory for elements with multiple (static) children. */
export declare function jsxs(
  type: string | Function | symbol,
  props: Record<string, unknown> | null,
  key?: string | number,
): unknown;

/** Automatic-runtime dev factory — same behavior as `jsx`/`jsxs`. */
export declare function jsxDEV(
  type: string | Function | symbol,
  props: Record<string, unknown> | null,
  key?: string | number,
  isStaticChildren?: boolean,
  source?: object,
  self?: unknown,
): unknown;

// TypeScript looks up a `JSX` namespace exported from the module referenced
// by `jsxImportSource` (i.e. this file) to type-check `.tsx` files.
export namespace JSX {
  interface IntrinsicElements {
    [elemName: string]: Record<string, any>;
  }

  interface ElementChildrenAttribute {
    children: Record<string, never>;
  }

  type Element = any;
}
